print("y = m₁x + b₁")
m1 = float(input('What is "m₁" ?'))
b1 = float(input('What is "b₁" ?'))
print(f"y = {m1}x + {b1}  ...⓵")
print("y = m₂x + b₂")
m2 = float(input('What is "m₂" ?'))
b2 = float(input('What is "b₂" ?'))
print(f"y = {m2}x + {b2}  ...⓶")
input("Press the ENTER/RETURN Key to continue")
print("\n\n\n\n\n\n\n")
print("Substitute y value in ⓶ with ⓵")
print(f"{m1}x + {b1} = {m2}x + {b2}")
input("Press the ENTER/RETURN Key to continue")
print("\n\n\n\n\n\n\n")
print(f"Move {m1}x + {b1} to the other side of the equal sign")
m3 = m2-m1
b3 = b2-b1
print(f"0 = {m3}x + {b3}")
input("Press the ENTER/RETURN Key to continue")
print("\n\n\n\n\n\n\n")
print(f"Isolate the {m3}x")
print(f"{-1*b3} = {m3}x")
x = (-1*b3)/m3
print(f"Thus, x = {x}")
input("Press the ENTER/RETURN Key to continue")
print("\n\n\n\n\n\n\n")
print(f"Substituting x = {x} into ⓵")
y = m1 * x + b1
print(f"y = {m1}*{x} + {b1}")
print(f"Thus, y = {y}")
input("Press the ENTER/RETURN Key to continue")
print("\n\n\n\n\n\n\n")
print(f"The point of intersection is ({x}, {y})")