#!/usr/bin/env python3
length_of_series = int(input('How many numbers are in your series?'))
first_num = float(input('What is the first number in your series?'))
last_num = float(input('What is the last number in your series?'))
print(f'\t\t\t\t{length_of_series}({first_num} + {last_num})')
print('n = -------------------------------------')
print('\t\t\t\t\t2')
e = input()
print(f'\t\t\t\t{length_of_series} * {first_num + last_num}')
print('n = -------------------------------------')
print('\t\t\t\t\t2')
e = input()
print(f'\t\t\t\t  {length_of_series*(first_num + last_num)}')
print('n = -------------------------------------')
print('\t\t\t\t\t2')
e = input()
print(f'n = {(length_of_series*(first_num + last_num))/2}')
e = input()
print(f'{(length_of_series * (first_num + last_num)) / 2} is the sum of the numbers in your series.')
